@startuml
left to right direction

skinparam dpi 300
'skinparam linetype ortho
skinparam nodesep 50
skinparam ranksep 50

skinparam default{
  FontSize 12
}

skinparam arrowFontSize 10
skinparam classFontSize 14

skinparam arrowSize 10

'''

:V: as "Viajero"

rectangle "Funcionalidades interactivas" {
    (Mandar mensaje) as mensaje
    (Publicar reseña) as reseña

    V -- mensaje
    V -- reseña
}

@enduml
