@startuml
left to right direction

skinparam dpi 300
'skinparam linetype ortho
skinparam nodesep 50
skinparam ranksep 50

skinparam default{
  FontSize 12
}

skinparam arrowFontSize 10
skinparam classFontSize 14

skinparam arrowSize 10

'''

:V: as "Viajero"

rectangle Usuario {
    (Registrar usuario) as registrar
    (Iniciar sesion) as iniciar_sesion
    (Gestionar perfil) as perfil
    (Gestionar métodos\nde pago) as gestionar_pagos
    (Borrar usuario) as borrar_usuario
    (Cerrar sesión) as cerrar_sesion

    V -- registrar
    V -- iniciar_sesion
    V -- cerrar_sesion
    V -- perfil
    perfil <.. gestionar_pagos : extend
    perfil <.. borrar_usuario : extend
    cerrar_sesion <.. borrar_usuario : include
}

@enduml
