@startuml
left to right direction

skinparam dpi 300
'skinparam linetype ortho
skinparam nodesep 50
skinparam ranksep 50

skinparam default{
 FontSize 12
}

skinparam arrowFontSize 10
skinparam classFontSize 14

skinparam arrowSize 10

'''

:V: as "Viajero"

rectangle "Reclamar deuda" {
   (Reclamar deuda) as reclamar_deuda

   V -- reclamar_deuda

   reclamar_deuda <.. (Seleccionar gasto) : include
   reclamar_deuda <.. (Seleccionar usuario) : include
   (Seleccionar usuario) <.. (Enviar notificación) : include
   reclamar_deuda <.. (Resolución externa) : extends 
}

'''

@enduml
