@startuml
left to right direction

skinparam dpi 300
'skinparam linetype ortho
skinparam nodesep 50
skinparam ranksep 50

skinparam default{
 FontSize 12
}

skinparam arrowFontSize 10
skinparam classFontSize 14

skinparam arrowSize 10

'''

:V: as "Viajero"

rectangle Grupos {
   (Gestionar participantes\ndel grupo) as participantes
   (Crear grupo de pago) as crear_grupo
   (Eliminar grupo de pago) as eliminar_grupo
   (Salir del grupo\nde pago) as salir_grupo

   V -down- participantes
   V -down- crear_grupo
   V -down- eliminar_grupo
   V -down- salir_grupo
   salir_grupo <.. eliminar_grupo : extend

   crear_grupo <.. (Introducir nombre) : include
   crear_grupo <.. (Introducir descripción) : include

   eliminar_grupo <.. (Confirmar eliminación) : include
}

rectangle "Agregar participantes" {
  (Añadir participantes) as agregar_participantes

  crear_grupo <.. agregar_participantes : extend
  participantes <.. agregar_participantes : extend

  agregar_participantes <.. (Seleccionar participantes) : include
}

@enduml
