@startuml
left to right direction

skinparam dpi 300
'skinparam linetype ortho
skinparam nodesep 50
skinparam ranksep 50

skinparam default{
 FontSize 12
}

skinparam arrowFontSize 10
skinparam classFontSize 14

skinparam arrowSize 10

'''

:V: as "Viajero"

rectangle "Gestionar métodos de pago" {
   (Gestionar métodos de pago) as gestionar_pagos
   (Añadir método de pago) as añadir_metodo
   (Eliminar método de pago) as eliminar_metodo
   (Modificar método de pago) as modificar_metodo

   V -- gestionar_pagos
   gestionar_pagos -- añadir_metodo 
   gestionar_pagos -- eliminar_metodo
   gestionar_pagos -- modificar_metodo

   añadir_metodo <.. (Seleccionar tipo de método) : include
   añadir_metodo <.. (Introducir datos del método) : include
   eliminar_metodo <.. (Confirmar eliminación) : include
   modificar_metodo <.. (Seleccionar método a modificar) : include
   modificar_metodo <.. (Introducir nuevos datos del método) : include
}

@enduml
