@startuml
left to right direction

skinparam dpi 300
'skinparam linetype ortho
skinparam nodesep 50
skinparam ranksep 50

skinparam default{
 FontSize 12
}

skinparam arrowFontSize 10
skinparam classFontSize 14

skinparam arrowSize 10

'''

:V: as "Viajero"

rectangle Registarse {
   (Registrar usuario) as registrar

   V -- registrar

   registrar <.. (Introducir datos personales) : include
   registrar <.. (Aceptar términos y condiciones) : include
   registrar <.. (Suscribirse a la newsletter) : extend
   registrar <.. (Verificar correo) : include
}

@enduml
