@startuml
left to right direction

skinparam dpi 300
'skinparam linetype ortho
skinparam nodesep 50
skinparam ranksep 50

skinparam default{
 FontSize 12
}

skinparam arrowFontSize 10
skinparam classFontSize 14

skinparam arrowSize 10

'''

:V: as "Viajero"

rectangle "Publicar reseña" {
   (Publicar reseña) as publicar

   V -- publicar

   publicar <.. (Publicar de forma anónima) : extend
   publicar <.. (Confirmar publicación) : include

    rectangle "Introducir datos de la reseña" {
       (Introducir datos de la reseña) as introducir

       publicar <.. introducir : include

       introducir <.. (Introducir título) : extend 
       introducir <.. (Introducir texto) : extend
       introducir <.. (Introducir puntuación) : extend
    }
}

@enduml
